***Assignment 2 - Working with Pandas***

# **1. Create a DataFrame with the following data:**  
  
  data = {
      'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
      'Age': [24, 27, 22, 32, 29],
      'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
      'Salary': [45000, 54000, 50000, 62000, 47000]
  }

In [17]:
# Importing Pandas
import pandas as pd

data = {
      'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
      'Age': [24, 27, 22, 32, 29],
      'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
      'Salary': [45000, 54000, 50000, 62000, 47000]
  }

# Converting Data into a Data-Frame using Pandas.
df = pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

## a. Print the first five rows of the DataFrame.

In [10]:
'''
Since the dataset has exactly five rows, df.head() will display the entire DataFrame.
If we had more rows, it would show only the first five by default.
'''
# Print the first five rows of the DataFrame.
df.head(5)

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

##  b. Get the summary statistics of the 'Age' and 'Salary' columns.

In [16]:
(df[['Age', 'Salary']].describe().round(2))

#This will display count, mean, std (standard deviation), min, max, and quartiles (25%, 50%, 75%) for both columns.

         Age    Salary
count   5.00      5.00
mean   26.80  51600.00
std     3.96   6730.53
min    22.00  45000.00
25%    24.00  47000.00
50%    27.00  50000.00
75%    29.00  54000.00
max    32.00  62000.00

## c. Calculate the average salary of employees in the 'HR' department.

In [18]:
avg_salary_hr = df[df['Department'] == 'HR']['Salary'].mean()
# This will filter only Alice and Eve (HR employees), then compute their average salary.

print("Average Salary of HR Department:", round(avg_salary_hr, 2))

Average Salary of HR Department: 46000.0

# **2. Add a new column, 'Bonus', which is 10% of the salary.**

In [19]:
df['Bonus'] = df['Salary']*0.1
print(df)

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
1      Bob   27    Finance   54000  5400.0
2  Charlie   22         IT   50000  5000.0
3    Diana   32  Marketing   62000  6200.0
4      Eve   29         HR   47000  4700.0

# **3. Filter the DataFrame to show employees aged between 25 and 30.**

In [23]:
filtered_df = df[(df['Age'] >= 25) & (df['Age'] <= 30)]
filtered_df

  Name  Age Department  Salary   Bonus
1  Bob   27    Finance   54000  5400.0
4  Eve   29         HR   47000  4700.0

# **4. Group the data by 'Department' and calculate the average salary for each department**

In [25]:
dept_sal_avg = df.groupby('Department')['Salary'].mean()
dept_sal_avg

Department
Finance      54000.0
HR           46000.0
IT           50000.0
Marketing    62000.0
Name: Salary, dtype: float64

# **5. Sort the DataFrame by 'Salary' in ascending order and save the result to a new CSV file.**

In [27]:
# Sort by Salary in ascending order
sorted_df = df.sort_values(by='Salary', ascending=True)

# Save to new CSV file
sorted_df.to_csv('sorted_salary.csv', index=False)

print(sorted_df)

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
4      Eve   29         HR   47000  4700.0
2  Charlie   22         IT   50000  5000.0
1      Bob   27    Finance   54000  5400.0
3    Diana   32  Marketing   62000  6200.0